export * from  './Register'
export * from './Login'
export * from './PrincipalPage'
export * from './SPO2PAGE'
export * from './FCPage'
export * from './HistorialOxigenoSangre'
export * from './HistorialFrecuenciaCardiaca'